#include <iostream>
#include <fstream>
#include <limits>
using namespace std;
/*
#################################################################
This program reads ascii art from a text file and then creates a text file
with the ascii art in a format that the c++ editor can read by adding cout << " at the beginning
and " << endl at the end
#####################################################################################

baby steps create a program that takes the argument that you entered and returns it
create a text file and write to it

Steps:
figuring out how to handle back slashes and double quotes within the ascii file (done)
be able to read a file path list with quotations (done)
    May need to remove the first and last quotations
change the new file name from bubbles(done)
now work on args input



options:
run the program with the compile, learn about arguments in order to specify a path to the text file.

big future:

make a refreshing terminal???
 (Notes Updates Progress)
//(5-26-2023) outputting a list of the current directory seems to be beyond my ability therefore we will be simply recieving the file location
// see error generated by File Path Test project

*/

void consoleWelcome();
string refinedFilePath(string);
void mainProcessing(string,ifstream*,ofstream*,bool);

int main(int argc, char* argv[])
{
    //void consoleWelecome();
    string filePath; //location of original art file entered
    string refinedPath;
    ifstream artFile;//original ascii file to be opened
    ofstream cppAsciiFile; // new format ascii


    //check for arguments if there are no arguments then get redirected to the main menue
    if(argc > 1){ //use argumet file path

        if(argc > 2){
            cout << "To many arguments " << endl;
        }else{

            for(int i =1;i < argc; i++)
            {
                filePath = filePath + argv[i];
            }
            mainProcessing(filePath,&artFile,&cppAsciiFile,false);
            cout << endl;
        }

    }else{ //if the argument is not used

        cout << endl;
        consoleWelcome();
            getline(cin,filePath);

            refinedPath = refinedFilePath(filePath);
            mainProcessing(refinedPath,&artFile,&cppAsciiFile,true);

            if(filePath[0] == '"'){cout << "First Character has quote " << '"' << endl;}
            else {cout << "no quote" << endl;};
            cout << "String Length " << filePath.length() << endl;
            cout << "Character Count " << artFile.gcount() << endl;
    }

    system("Pause");
    return 0;
}


string refinedFilePath(string userInputPath){
    string refinedPath;
    for(char x: userInputPath){
        if(x != '"'){refinedPath = refinedPath + x;};
    }
     return refinedPath;
}

void mainProcessing(string filePath, ifstream* artFile, ofstream* cppAsciiFile,bool display ){
    cout << "This is the entered File Path\n " << filePath << endl;
            artFile->open(filePath); // opens the ascii art file
            cout << "Opened File Path" << endl; ///
            string artLine; //formerly testLine
            string outputType = "cout";//default output type

            if(artFile->is_open()){

                if(display){
                    cout << "Text file that is being edited " << endl << artFile->rdbuf() << endl;
                artFile->clear();
                artFile->seekg(0);
                }


                cout << "would you like to replace cout ? (y/n)\n <->>>";
                char response;
                string replacement;
                cin >> response;
                if(response == 'y'){
                    cout << "What would you like to replace cout with ? \n<->>>";
                    cin >> replacement;
                    outputType = replacement;
                }
                //take input to replace cout
                //assign the cout type a variable
                cppAsciiFile->open("asciiCpp.txt");
                cout << "Creating & Opening asciiCpp.txt file " << endl;
                if(cppAsciiFile->is_open()){
                        while(getline(*artFile,artLine)){

                                *cppAsciiFile << outputType << " << " << '"';

                            for(char c : artLine){
                                if(c == '"' || c == '\\'){
                                *cppAsciiFile << "\\";
                                }
                                *cppAsciiFile << c;
                            }
                            *cppAsciiFile << '"' << " << endl;" << endl;
                        }

                }else{
                    cout << "\nOUTPUT FILE FAILED TO OPEN\n" << endl;
                }

            }else{
                cout << "\nFAILED TO OPEN ORIGINAL FILE PATH\n" << endl;
            }

            artFile->close();
            cppAsciiFile->close();
}


void consoleWelcome(){
    cout << "$$___$$___________$$__________________________________" << endl;
    cout << "$$___$$__$$$$_____$$_____$$$$____$$$$___$$$$$$___$$$$_" << endl;
    cout << "$$_$_$$_$$__$$____$$____$$__$$__$$__$$__$$_$_$$_$$__$$" << endl;
    cout << "$$_$_$$_$$__$$____$$____$$______$$__$$__$$_$_$$_$$__$$" << endl;
    cout << "$$_$_$$_$$$$$$____$$____$$______$$__$$__$$_$_$$_$$$$$$" << endl;
    cout << "_$$_$$__$$________$$____$$______$$__$$__$$_$_$$_$$____" << endl;
    cout << "_$$_$$__$$________$$____$$__$$__$$__$$__$$_$_$$_$$____" << endl;
    cout << "_$$_$$___$$$$___$$$$$$___$$$$____$$$$___$$___$$__$$$$\n" << endl;

    cout << "NOTES & REMINDERS" << endl;
    cout << "### To copy the file location of a text file use (CTRL + SHIFT + C) combination \n (*with the file selected) \n";
    cout << "OR use (SHIFT + LeftClick) and select copy as Path" << endl;
    cout << "##The asciiCpp.txt file will be generated in the same directory that the program was run in.\n\n";
    cout << "Welcome enter the file Path for your ASCII art below \n-> ";
}
